### ISSUE TITLE
Issue with encrypth files

### ISSUE THREAD

**Issue by Kotamba2** [DuelitDev/ModsPlease#2]
python packer.py -e C:\Users\******\Downloads\PapersPlease\assets\Z\output\assets C:\Users\******\Downloads\PapersPlease\assets

Traceback (most recent call last):
  File "C:\Users\******\packer.py", line 194, in <module>
    pack(*sys.argv[2:4])
  File "C:\Users\******\\packer.py", line 93, in pack
    header += str(len(s2p(files[0]))).encode("utf-8") + b":"
                          ~^^^
IndexError: list index out of range

**Comment by devrelu** [comment]
I think `.../Z/output/assets` is an empty folder.

## Step to reproduce
```powershell
PS D:\dev\ModsPlease> python --version
Python 3.12.5
PS D:\dev\ModsPlease> ls

    Directory: D:\dev\ModsPlease

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---        2024-09-04 오후 10:16           6481 packer.py

PS D:\dev\ModsPlease> mkdir output

    Directory: D:\dev\ModsPlease

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----        2024-09-04 오후 10:26                output

PS D:\dev\ModsPlease> python packer.py -e output Art.dat
Traceback (most recent call last):
  File "D:\dev\ModsPlease\packer.py", line 194, in <module>
    pack(*sys.argv[2:4])
  File "D:\dev\ModsPlease\packer.py", line 93, in pack
    header += str(len(s2p(files[0]))).encode("utf-8") + b":"
                          ~~~~~^^^
IndexError: list index out of range
PS D:\dev\ModsPlease>
```

**Comment by Kotamba2** [comment]
thx, there is another problem:

C:\Windows\system32>python packer.py -e C:\Users\user\Downloads\PapersPlease\assets\Z\output C:\Users\user\Downloads\PapersPlease\assets
Traceback (most recent call last):
  File "C:\Windows\system32\packer.py", line 194, in <module>
    pack(*sys.argv[2:4])
  File "C:\Windows\system32\packer.py", line 116, in pack
    with open(output_file, "wb") as output:
         ^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\-----\\Downloads\\PapersPlease\\assets'

**Comment by devrelu** [comment]
The error occurs because `C:\Users\user\Downloads\PapersPlease\assets` is a folder.
The second argument must be a folder and the third argument must be a file.

## Step to reproduce
```powershell
PS D:\dev\ModsPlease> ls

    Directory: D:\dev\ModsPlease

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----        2024-09-05  오전 2:53                assets
d----        2024-09-05  오전 2:51                output
-a---        2024-09-04  오후 9:51        2882176 Art.dat
-a---        2024-09-04 오후 10:16           6481 packer.py

PS D:\dev\ModsPlease> type assets
Get-Content: Unable to get content because it is a directory:  
'D:\dev\ModsPlease\assets'. Please use 'Get-ChildItem' instead.

PS D:\dev\ModsPlease> python packer.py -e output assets
Traceback (most recent call last):
  File "D:\dev\ModsPlease\packer.py", line 194, in <module>
    pack(*sys.argv[2:4])
  File "D:\dev\ModsPlease\packer.py", line 116, in pack
    with open(output_file, "wb") as output:
         ^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'assets'
PS D:\dev\ModsPlease>
```

**Comment by Kotamba2** [comment]
Oh thank you, it works
But... I think I need a more detailed guide, as a layman I would never have guessed the solution without your help. And I'm sure I'm not the only one
